# Generated by Django 5.1.2 on 2024-11-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ACCESORIOS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruedas',
            name='Anio',
            field=models.IntegerField(default=2024),
        ),
        migrations.AddField(
            model_name='ruedas',
            name='Fecha_carga',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
